Use -lext on Windows (required at least for msvcrt build) Fixes: undefined reference to `regexec' undefined reference to `regfree' undefined reference to `regcomp'